In [1]:
import pandas as pd

In [2]:
import requests

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

## Vector spaces
- Turn the documents into vectors
- Term document matrix:
    - Each row is a document
-Each column is a word/token
- bag of words:
    - word order is lost
    - sparse matrix

In [3]:
df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])
df.head()

course                           section  \
0  data-engineering-zoomcamp  General course-related questions   
1  data-engineering-zoomcamp  General course-related questions   
2  data-engineering-zoomcamp  General course-related questions   
3  data-engineering-zoomcamp  General course-related questions   
4  data-engineering-zoomcamp  General course-related questions   

                                            question  \
0               Course - When will the course start?   
1  Course - What are the prerequisites for this c...   
2  Course - Can I still join the course after the...   
3  Course - I have registered for the Data Engine...   
4   Course - What can I do before the course starts?   

                                                text  
0  The purpose of this document is to capture fre...  
1  GitHub - DataTalksClub data-engineering-zoomca...  
2  Yes, even if you don't register, you're still ...  
3  You don't need it. You're accepted. You can al...  
4  You can start by installing and setting up all...

In [4]:
df.course.unique()

array(['data-engineering-zoomcamp', 'machine-learning-zoomcamp',
       'mlops-zoomcamp'], dtype=object)

In [5]:
df[df.course == 'machine-learning-zoomcamp'].head(-5)

course                           section  \
435  machine-learning-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
438  machine-learning-zoomcamp  General course-related questions   
439  machine-learning-zoomcamp  General course-related questions   
..                         ...                               ...   
800  machine-learning-zoomcamp                     Miscellaneous   
801  machine-learning-zoomcamp                     Miscellaneous   
802  machine-learning-zoomcamp                     Miscellaneous   
803  machine-learning-zoomcamp                     Miscellaneous   
804  machine-learning-zoomcamp                     Miscellaneous   

                                              question  \
435                                  How do I sign up?   
436                      Is it going to be live? When?   
437                          What if I miss a session?   
438                    How much theory will you cover?   
439          I don't know math. Can I take the course?   
..                                                 ...   
800                          Features in scikit-learn?   
801  When I plotted using Matplot lib to check if m...   
802                    Reproducibility in different OS   
803                         Deploying to Digital Ocean   
804  Is it best to train your model only on the mos...   

                                                  text  
435  Machine Learning Zoomcamp FAQ\nThe purpose of ...  
436  The course videos are pre-recorded, you can st...  
437  Everything is recorded, so you won’t miss anyt...  
438  The bare minimum. The focus is more on practic...  
439  Yes! We'll cover some linear algebra in the co...  
..                                                 ...  
800  Features (X) must always be formatted as a 2-D...  
801  FutureWarning: is_categorical_dtype is depreca...  
802  When trying to rerun the docker file in Window...  
803  You may quickly deploy your project to Digital...  
804  I’m just looking back at the lessons in week 3...  

[370 rows x 4 columns]

In [6]:
docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(stop_words='english')
X = cv.fit_transform(docs_example)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.todense(), columns=names).T
df_docs

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
X = cv.fit_transform(docs_example)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names).T
df_docs

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english' ,min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.todense(), columns=names)
df_docs

01  02  03  04  05  06  09  10  100  11  ...  y_val  yaml  year  yellow  \
0     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
1     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
2     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
3     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
4     0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ...    ...   ...   ...     ...   
943   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
944   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
945   0   0   0   0   0   0   0   0    0   0  ...      0     1     0       0   
946   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   
947   0   0   0   0   0   0   0   0    0   0  ...      0     0     0       0   

     yellow_tripdata_2021  yes  yml  youtube  zip  zoomcamp  
0                       0    0    0        0    0         0  
1                       0    0    0        0    0         1  
2                       0    1    0        0    0         0  
3                       0    0    0        0    0         0  
4                       0    0    0        0    0         0  
..                    ...  ...  ...      ...  ...       ...  
943                     0    0    1        0    0         0  
944                     0    0    0        0    0         0  
945                     0    0    0        0    0         0  
946                     0    0    0        0    0         0  
947                     0    0    0        0    0         1  

[948 rows x 1333 columns]

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english' ,min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.todense(), columns=names)
df_docs

01   02   03   04   05   06   09   10  100   11  ...  y_val      yaml  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...       ...   
943  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
944  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
945  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.167274   
946  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   
947  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.000000   

     year  yellow  yellow_tripdata_2021       yes       yml  youtube  zip  \
0     0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
1     0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
2     0.0     0.0                   0.0  0.279891  0.000000      0.0  0.0   
3     0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
4     0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
..    ...     ...                   ...       ...       ...      ...  ...   
943   0.0     0.0                   0.0  0.000000  0.107298      0.0  0.0   
944   0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
945   0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
946   0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   
947   0.0     0.0                   0.0  0.000000  0.000000      0.0  0.0   

     zoomcamp  
0    0.000000  
1    0.428961  
2    0.000000  
3    0.000000  
4    0.000000  
..        ...  
943  0.000000  
944  0.000000  
945  0.000000  
946  0.000000  
947  0.148428  

[948 rows x 1333 columns]

# Query-Document Similarity

In [12]:
query = "Do I need to know python to sign up for the January course?"

q = cv.transform([query])
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [13]:
query_dict = dict(zip(names, q.toarray()[0]))
query_dict

{'01': 0.0,
 '02': 0.0,
 '03': 0.0,
 '04': 0.0,
 '05': 0.0,
 '06': 0.0,
 '09': 0.0,
 '10': 0.0,
 '100': 0.0,
 '11': 0.0,
 '12': 0.0,
 '127': 0.0,
 '13': 0.0,
 '14': 0.0,
 '15': 0.0,
 '16': 0.0,
 '17': 0.0,
 '19': 0.0,
 '1st': 0.0,
 '20': 0.0,
 '2019': 0.0,
 '2020': 0.0,
 '2021': 0.0,
 '2022': 0.0,
 '2023': 0.0,
 '2024': 0.0,
 '21': 0.0,
 '22': 0.0,
 '24': 0.0,
 '25': 0.0,
 '2pacx': 0.0,
 '30': 0.0,
 '35': 0.0,
 '403': 0.0,
 '42': 0.0,
 '50': 0.0,
 '5000': 0.0,
 '5431': 0.0,
 '5432': 0.0,
 '60': 0.0,
 '600': 0.0,
 '7077': 0.0,
 '80': 0.0,
 '8080': 0.0,
 '8888': 0.0,
 '9696': 0.0,
 'abhijit': 0.0,
 'able': 0.0,
 'abolade': 0.0,
 'absolute': 0.0,
 'accept': 0.0,
 'access': 0.0,
 'accordingly': 0.0,
 'account': 0.0,
 'accuracy': 0.0,
 'action': 0.0,
 'activate': 0.0,
 'actual': 0.0,
 'actually': 0.0,
 'add': 0.0,
 'added': 0.0,
 'adding': 0.0,
 'addition': 0.0,
 'additional': 0.0,
 'additionally': 0.0,
 'address': 0.0,
 'admin': 0.0,
 'advani': 0.0,
 'ahmed': 0.0,
 'ai': 0.0,
 'airflow': 0

In [14]:
doc_dict = dict(zip(names, X.toarray()[1]))
doc_dict

{'01': 0.0,
 '02': 0.0,
 '03': 0.0,
 '04': 0.0,
 '05': 0.0,
 '06': 0.0,
 '09': 0.0,
 '10': 0.0,
 '100': 0.0,
 '11': 0.0,
 '12': 0.0,
 '127': 0.0,
 '13': 0.0,
 '14': 0.0,
 '15': 0.0,
 '16': 0.0,
 '17': 0.0,
 '19': 0.0,
 '1st': 0.0,
 '20': 0.0,
 '2019': 0.0,
 '2020': 0.0,
 '2021': 0.0,
 '2022': 0.0,
 '2023': 0.0,
 '2024': 0.0,
 '21': 0.0,
 '22': 0.0,
 '24': 0.0,
 '25': 0.0,
 '2pacx': 0.0,
 '30': 0.0,
 '35': 0.0,
 '403': 0.0,
 '42': 0.0,
 '50': 0.0,
 '5000': 0.0,
 '5431': 0.0,
 '5432': 0.0,
 '60': 0.0,
 '600': 0.0,
 '7077': 0.0,
 '80': 0.0,
 '8080': 0.0,
 '8888': 0.0,
 '9696': 0.0,
 'abhijit': 0.0,
 'able': 0.0,
 'abolade': 0.0,
 'absolute': 0.0,
 'accept': 0.0,
 'access': 0.0,
 'accordingly': 0.0,
 'account': 0.0,
 'accuracy': 0.0,
 'action': 0.0,
 'activate': 0.0,
 'actual': 0.0,
 'actually': 0.0,
 'add': 0.0,
 'added': 0.0,
 'adding': 0.0,
 'addition': 0.0,
 'additional': 0.0,
 'additionally': 0.0,
 'address': 0.0,
 'admin': 0.0,
 'advani': 0.0,
 'ahmed': 0.0,
 'ai': 0.0,
 'airflow': 0

In [15]:
df_qd = pd.DataFrame([query_dict, doc_dict], index=['query', 'doc']).T

(df_qd['query'] * df_qd['doc']).sum()

0.0

In [16]:
X.dot(q.T).toarray()

array([[0.19464486],
       [0.        ],
       [0.        ],
       [0.06011641],
       [0.04932915],
       [0.        ],
       [0.        ],
       [0.13477565],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.15899187],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.07431408],
       [0.        ],
       [0.        ],
       [0.05779673],
       [0.07243428],
       [0.        ],
       [0.05174293],
       [0.16373635],
       [0.08076031],
       [0.        ],
       [0.09755254],
       [0.        ],
       [0.21069625],
       [0.12067781],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.06381749],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.00910541],
       [0.02835681],
       [0.05480112],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.024

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(X, q)

array([[0.19464486],
       [0.        ],
       [0.        ],
       [0.06011641],
       [0.04932915],
       [0.        ],
       [0.        ],
       [0.13477565],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.15899187],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.07431408],
       [0.        ],
       [0.        ],
       [0.05779673],
       [0.07243428],
       [0.        ],
       [0.05174293],
       [0.16373635],
       [0.08076031],
       [0.        ],
       [0.09755254],
       [0.        ],
       [0.21069625],
       [0.12067781],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.06381749],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.00910541],
       [0.02835681],
       [0.05480112],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.024

In [18]:
fields = ['section', 'question', 'text']
transformers = {}
matrices = {}

for field in fields:
    cv = TfidfVectorizer(stop_words='english', min_df=3)
    X = cv.fit_transform(df[field])

    transformers[field] = cv
    matrices[field] = X

transformers['text'].get_feature_names_out()
matrices['text']

<948x2118 sparse matrix of type '<class 'numpy.float64'>'
	with 26463 stored elements in Compressed Sparse Row format>

In [19]:
matrices, transformers

({'section': <948x67 sparse matrix of type '<class 'numpy.float64'>'
  	with 3094 stored elements in Compressed Sparse Row format>,
  'question': <948x562 sparse matrix of type '<class 'numpy.float64'>'
  	with 4333 stored elements in Compressed Sparse Row format>,
  'text': <948x2118 sparse matrix of type '<class 'numpy.float64'>'
  	with 26463 stored elements in Compressed Sparse Row format>},
 {'section': TfidfVectorizer(min_df=3, stop_words='english'),
  'question': TfidfVectorizer(min_df=3, stop_words='english'),
  'text': TfidfVectorizer(min_df=3, stop_words='english')})

In [20]:
query = "I just signed up. Is it too late to join the course?"

q = transformers['text'].transform([query])
score = cosine_similarity(matrices['text'], q).flatten()

In [21]:
mask = (df.course == 'data-engineering-zoomcamp').values
score = score * mask

In [22]:
import numpy as np

idx = np.argsort(-score)[:10]

In [23]:
df.iloc[idx].text

0      The purpose of this document is to capture fre...
15     No, late submissions are not allowed. But if t...
22     It's up to you which platform and environment ...
27     You can do most of the course without a cloud....
38     You will have two attempts for a project. If t...
287    This error could result if you are using some ...
3      You don't need it. You're accepted. You can al...
7      Yes, we will keep all the materials after the ...
113    In the join queries, if we mention the column ...
11     No, you can only get a certificate if you fini...
Name: text, dtype: object

In [24]:
score = np.zeros(len(df), dtype=float)
query = "I just signed up. Is it too late to join the course?"

for field in fields:
    q = transformers[field].transform([query])
    score += cosine_similarity(matrices[field], q).flatten()

In [25]:
idx = np.argsort(-score)[:10]
df.iloc[idx]

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
1    data-engineering-zoomcamp  General course-related questions   
34   data-engineering-zoomcamp  General course-related questions   
4    data-engineering-zoomcamp  General course-related questions   
5    data-engineering-zoomcamp  General course-related questions   
9    data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
452  machine-learning-zoomcamp  General course-related questions   
448  machine-learning-zoomcamp  General course-related questions   

                                              question  \
0                 Course - When will the course start?   
1    Course - What are the prerequisites for this c...   
34                How can we contribute to the course?   
4     Course - What can I do before the course starts?   
5               Course - how many Zoomcamps in a year?   
9    Course - Which playlist on YouTube should I re...   
7    Course - Can I follow the course after it fini...   
449  The course has already started. Can I still jo...   
452  I just joined. What should I do next? How can ...   
448  I’m new to Slack and can’t find the course cha...   

                                                  text  
0    The purpose of this document is to capture fre...  
1    GitHub - DataTalksClub data-engineering-zoomca...  
34   Star the repo! Share it with friends if you fi...  
4    You can start by installing and setting up all...  
5    There are 3 Zoom Camps in a year, as of 2024. ...  
9    All the main videos are stored in the Main “DA...  
7    Yes, we will keep all the materials after the ...  
449  Yes, you can. You won’t be able to submit some...  
452  Welcome to the course! Go to the course page (...  
448  Here’s how you join a in Slack: https://slack....

In [26]:
filters = {
    'course': 'data-engineering-zoomcamp'
}

In [27]:
for field, value in filters.items():
    mask = (df[field] == value).astype(int).values
    score = score * mask

In [28]:
idx = np.argsort(-score)[:10]
df.iloc[idx]

course                           section  \
0   data-engineering-zoomcamp  General course-related questions   
1   data-engineering-zoomcamp  General course-related questions   
4   data-engineering-zoomcamp  General course-related questions   
5   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
9   data-engineering-zoomcamp  General course-related questions   
7   data-engineering-zoomcamp  General course-related questions   
2   data-engineering-zoomcamp  General course-related questions   
8   data-engineering-zoomcamp  General course-related questions   
10  data-engineering-zoomcamp  General course-related questions   

                                             question  \
0                Course - When will the course start?   
1   Course - What are the prerequisites for this c...   
4    Course - What can I do before the course starts?   
5              Course - how many Zoomcamps in a year?   
34               How can we contribute to the course?   
9   Course - Which playlist on YouTube should I re...   
7   Course - Can I follow the course after it fini...   
2   Course - Can I still join the course after the...   
8   Course - Can I get support if I take the cours...   
10  Course - ​​How many hours per week am I expect...   

                                                 text  
0   The purpose of this document is to capture fre...  
1   GitHub - DataTalksClub data-engineering-zoomca...  
4   You can start by installing and setting up all...  
5   There are 3 Zoom Camps in a year, as of 2024. ...  
34  Star the repo! Share it with friends if you fi...  
9   All the main videos are stored in the Main “DA...  
7   Yes, we will keep all the materials after the ...  
2   Yes, even if you don't register, you're still ...  
8   Yes, the slack channel remains open and you ca...  
10  It depends on your background and previous exp...

In [29]:
score = np.zeros(len(df), dtype=float)
query = "I just signed up. Is it too late to join the course?"
boost = { 'question': 3.0,
             # 'section': 0.5,
    # 'text': 2.0
        }

for field in fields:
    q = transformers[field].transform([query])
    f_score =  cosine_similarity(matrices[field], q).flatten()
    score += f_score * boost.get(field, 1.0)

In [30]:
ilters = {
    'course': 'data-engineering-zoomcamp'
}
for field, value in filters.items():
    mask = (df[field] == value).astype(int).values
    score = score * mask
idx = np.argsort(-score)[:5]
df.iloc[idx]

course                           section  \
1   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
4   data-engineering-zoomcamp  General course-related questions   
5   data-engineering-zoomcamp  General course-related questions   
9   data-engineering-zoomcamp  General course-related questions   

                                             question  \
1   Course - What are the prerequisites for this c...   
34               How can we contribute to the course?   
4    Course - What can I do before the course starts?   
5              Course - how many Zoomcamps in a year?   
9   Course - Which playlist on YouTube should I re...   

                                                 text  
1   GitHub - DataTalksClub data-engineering-zoomca...  
34  Star the repo! Share it with friends if you fi...  
4   You can start by installing and setting up all...  
5   There are 3 Zoom Camps in a year, as of 2024. ...  
9   All the main videos are stored in the Main “DA...

In [31]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [32]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just signed up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [33]:
from sklearn.decomposition import TruncatedSVD

X = matrices['text']
cv = transformers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.08800519, -0.07539671, -0.102656  ,  0.05231696,  0.04962812,
       -0.05976404,  0.02248738,  0.02935992, -0.18680275,  0.3292944 ,
        0.0839041 ,  0.10218709, -0.07440421,  0.07475562, -0.0268979 ,
        0.01029371])

In [34]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.04353808, -0.03082846, -0.04502356,  0.01208928,  0.02495009,
       -0.05035307,  0.01209961,  0.02196586, -0.11364409,  0.17793184,
        0.05710037,  0.0795884 , -0.05401487,  0.02711403, -0.01714215,
       -0.00160826])

In [35]:
np.dot(X_emb[0], Q_emb[0])

0.11581013086783695

In [36]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
449  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
7    data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
13   data-engineering-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
15   data-engineering-zoomcamp  General course-related questions   

                                              question  \
764  What If I submitted only two projects and fail...   
449  The course has already started. Can I still jo...   
814  What if my answer is not exactly the same as t...   
7    Course - Can I follow the course after it fini...   
0                 Course - When will the course start?   
451      Can I submit the homework after the due date?   
13   Office Hours - I can’t attend the “Office hour...   
436                      Is it going to be live? When?   
11   Certificate - Can I follow the course in a sel...   
15   Homework - Are late submissions of homework al...   

                                                  text  
764  If you have submitted two projects (and peer-r...  
449  Yes, you can. You won’t be able to submit some...  
814  Please choose the closest one to your answer. ...  
7    Yes, we will keep all the materials after the ...  
0    The purpose of this document is to capture fre...  
451  No, it’s not possible. The form is closed afte...  
13   Yes! Every “Office Hours” will be recorded and...  
436  The course videos are pre-recorded, you can st...  
11   No, you can only get a certificate if you fini...  
15   No, late submissions are not allowed. But if t...

# Non-Negative Matrix Factorization

In [37]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.30670117,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [38]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]

array([0.        , 0.00114414, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.17139313,
       0.        , 0.        , 0.        , 0.        , 0.00064294,
       0.        ])

In [39]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
0    data-engineering-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
2    data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
436  machine-learning-zoomcamp  General course-related questions   
437  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   

                                              question  \
0                 Course - When will the course start?   
814  What if my answer is not exactly the same as t...   
2    Course - Can I still join the course after the...   
451      Can I submit the homework after the due date?   
449  The course has already started. Can I still jo...   
764  What If I submitted only two projects and fail...   
436                      Is it going to be live? When?   
437                          What if I miss a session?   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   

                                                  text  
0    The purpose of this document is to capture fre...  
814  Please choose the closest one to your answer. ...  
2    Yes, even if you don't register, you're still ...  
451  No, it’s not possible. The form is closed afte...  
449  Yes, you can. You won’t be able to submit some...  
764  If you have submitted two projects (and peer-r...  
436  The course videos are pre-recorded, you can st...  
437  Everything is recorded, so you won’t miss anyt...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...

# BERT

In [40]:
pip install transformers tqdm torch

Note: you may need to restart the kernel to use updated packages.


In [41]:
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [42]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

In [43]:
with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state

In [44]:
sentence_embeddings = hidden_states.mean(dim=1)
sentence_embeddings.shape

torch.Size([2, 768])

In [45]:
X_emb = sentence_embeddings.numpy()

In [47]:
def make_batches(seq, n):
    result = []
    for i in range(0, len(seq), n):
        batch = seq[i:i+n]
        result.append(batch)
    return result

In [48]:
from tqdm.auto import tqdm

In [49]:
def compute_embeddings(texts, batch_size=8):
    text_batches = make_batches(texts, 8)

    all_embeddings = []

    for batch in tqdm(text_batches):
        encoded_input = tokenizer(batch, padding=True, truncation=True, return_tensors='pt')

        with torch.no_grad():
            outputs = model(**encoded_input)
            hidden_states = outputs.last_hidden_state

            batch_embeddings = hidden_states.mean(dim=1)
            batch_embeddings_np = batch_embeddings.cpu().numpy()
            all_embeddings.append(batch_embeddings_np)

    final_embeddings = np.vstack(all_embeddings)
    return final_embeddings

In [50]:
embeddings = {}

In [51]:
for f in fields:
    print(f'computing embeddings for {f}...')
    embeddings[f] = compute_embeddings(df[f].tolist())

computing embeddings for section...


  0%|          | 0/119 [00:00<?, ?it/s]

computing embeddings for question...


  0%|          | 0/119 [00:00<?, ?it/s]

computing embeddings for text...


  0%|          | 0/119 [00:00<?, ?it/s]